---
image: docker:19.03.1
services:
  - docker:19.03.1-dind

stages:
  - Build and Push Image

variables:
  BASE_BUILD_IMAGE: ${CI_REGISTRY_IMAGE}
  REF_TAG: ${CI_COMMIT_REF_NAME}
  BUILD_ID: ${CI_PIPELINE_ID}
  IMAGE_SOURCE_REPOSITORY: ${CI_PROJECT_URL}
  IMAGE_REVISION: ${CI_COMMIT_SHA}

before_script:
  - echo "${CI_REGISTRY_PASSWORD}" | docker login --username ${CI_REGISTRY_USER} --password-stdin $CI_REGISTRY

after_script:
  - docker logout $CI_REGISTRY

.build-and-push:
  script:
    - ./script/common/build.sh
    - ./script/common/push.sh
  allow_failure: false

Build and Push - Alpine:
  stage: Build and Push Image
  variables:
    VARIANT: alpine
  extends: 
    - .build-and-push
